apiVersion: v1
kind: Service
metadata:
  name: sa-web-app-lb
  namespace: prod-namespace
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: sa-web-app
